import { FaFacebook } from 'react-icons/fa6';

function FBLoginBtn() {
  const handleFacebookLogin = () => {
    // Construct the full absolute URL to the backend's Facebook auth endpoint.
    // This prevents the browser from using the frontend's domain, which can cause
    // incorrect callback URLs to be generated by Passport.js.
    const backendUrl = `${import.meta.env.VITE_API_BASE_URL}/auth/facebook`;
    window.location.href = backendUrl;
  };

  return (
    <button
      className="min-w-[180px] sm:max-w-[400px] flex items-center justify-center  border bg-white  border-gray-300 text-gray-700 text-lg sm:text-base  hover:border-blue-400 hover:text-blue-600 py-2.5 sm:py-3 md:py-2.5 sm:px-5 gap-1 rounded-md tracking-wide font-medium cursor-pointer transition ease-in duration-500"
      type="button"
      onClick={handleFacebookLogin}
    >
      <FaFacebook className="text-2xl text-blue-600" />
      <span>Facebook</span>
    </button>
  );
}

export default FBLoginBtn;
